# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Размышления программиста
email: r@kamenskiy.net
description: > # this means to ignore newlines until "baseurl:"
  Блог о разработке ПО и всяком таком
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.kamenskiy.net" # the base hostname & protocol for your site
twitter_username: r_kamenskiy
github_username:  r-kamenskiy

# Build settings
markdown: kramdown